#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration,
#displays Best School and then Hi on a new line.
c=1
while [ $c -le 10 ]
do
	if [ $c -eq 9 ];
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((c++))
done
